[package]
name = "http"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.14", default-features = false, features = ["json", "socks"] }
async-stream = { version = "0.3.2" }
async-trait = { version = "0.1.88" }
futures = { version = "0.3.31" }
serde = { version = "1.0.219", default-features = false }
serde_json = "1.0.140"
thiserror = "2.0.12"
log = "0.4.26"